name: CI (build and test)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.11", "3.12"]
    name: "Core, Python ${{ matrix.python-version }}, ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      # 🧹 Free up disk space at the start
      - name: Free up disk space
        run: |
          echo "Initial disk space:"
          df -h

          echo "Removing large pre-installed tools..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          echo "Disk space after cleanup:"
          df -h

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package
        run: python -m pip install -e .[dev,stardist]

      - name: Check if manifest has changed
        run: fractal-manifest check --package abbott

      - name: Test core library with pytest
        run: python -m pytest tests 

      # 🐳 Clean up Docker & any leftover space at the end
      - name: Clean up Docker
        if: always()
        run: |
          docker system prune -af --volumes || true
          echo "Disk space after Docker cleanup:"
          df -h

  deploy:
    name: Deploy
    needs: tests
    if: success() && startsWith(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing on PyPi
      # see https://docs.pypi.org/trusted-publishers/
      id-token: write
      # This permission allows writing releases
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 👷 Build
        run: |
          python -m pip install build
          python -m build

      - name: 🚢 Publish to PyPI
        # TODO remove the "if: false" line when the package is ready for pypi release
        if: false
        uses: pypa/gh-action-pypi-publish@release/v1

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: './dist/*'